### ISSUE TITLE
This repo doesn't meet the "durable ownership minimums" for Microsoft compliance

### ISSUE THREAD

**Issue by jdubois** [Azure-Samples/js-e2e-express-server#38]
I've been pinged as this repo doesn't meet the "durable ownership minimums" for Microsoft compliance.
Please add another owner to this repo to meet those requirements!
I'll check this in 2 weeks, if the requirements are not met, I'll add myself as an owner, and archive the repo.

**Comment by diberry** [comment]
This is fixed now.
