### ISSUE TITLE
azure webapp :( Application Error

### ISSUE THREAD

**Issue by calvinShan** [Azure-Samples/js-e2e-express-server#40]
Hello

 I used this nodejs, i run these commands to deploy app to public webapp(webapp Node - 18-lts standard)
Publishing model: Code

npm install
az account set --subscription "xx"
az webapp up --sku P1V3 --name app-xx --os-type Linux

this nodejs works well locally, however, when I reach the webapp endpoint, here is the error

:( Application Error
If you are the application administrator, you can access the diagnostics

HTTP server errors : 503 Server Unavailable
Container issue : app timed out
Applications logs
Web App Troubleshooter : App Container Failed to Start
Web App Restarted
Docker image or framework version change was found
Your application was recycled due to either framework version or docker image name has changed

Do you know why it does not work on webapp azure?

Thanks

**Comment by diberry** [comment]
I assume this was an issue with the WEB_PORT versus PORT env variable name. Please see new information in the readme.
